### ISSUE TITLE
The sentence construction differs for MSG_SEARCH_IN_IT_ISARE and MSG_SEARCH_ON_IT_ISARE

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#101]
I don't know if it's intentional, but the construction of the answer to 'look on' and 'look in' are different :
```
> look on table                                                 
On the table is a apple.

> look in box                                                   
The box contains a pear. 
```
Instead of : "In the box is a pear."

**Comment by fredrikr** [comment]
This is intentional. The choice between printing "is" or "are" is tricky and will sometimes yield sub-optimal results. For containers this can easily be avoided. For supporters we're stuck with using is/are.
