### ISSUE TITLE
Can with_key be a routine?

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#11]
I just posted this issue on the I6 library repository. Since it's a request to support a behavior that the compiler doesn't complain about (and it's not affecting anyone else's code), I'm also requesting it here, regardless of the decision made for the I6 lib :) I'll add that it'd be great in order to save space: I'm currently folding 10 doors into one object to economize on objects, and this feature would be good (if not, I'll find a hack to make it work, but...)

Can with_key be a routine? e.g.
Object doorToApartment
   with short_name [; if (divorce_happened) { return "Door to our apartment"; } else { return "Door to her apartement";} ],
   with_key [; if (divorce_happened) { return newkey; } else { return oldkey; } ],

It's not specified in the DM4 or anywhere else, from what I can see. The compiler never complains either.

It would make sense, though, since there are several other properties in inform (cantgo, n_to, door_to, door_dir, etc) that are either the name of an object or a routine that returns an object. However, currently, in grammar.h, the LockSub and UnlockSub only check (I'm paraphrasing here)
   "if (noun.with_key ~= second) { "Doesn't fit."; }"

Can we generalize the code so that both an object name or a routine that returns an object can be supported?

**Comment by ByteProject** [comment]
+1 from my side, would be a great feature!

**Comment by fredrikr** [comment]
This feature has now been added to PunyInform. Additionally, the library promises that the object currently being considered as the key is held in 'second'. This allows the routine to accept different keys, like this:

Object KitchenDoor "door"
 with
  ...
    with_key [;
      if(second==KitchenKey or MasterKey) return second;
    ],
  has ... ;
