### ISSUE TITLE
Auto-guess noun improvements

### ISSUE THREAD

**Issue by fredrikr** [johanberntsson/PunyInform#112]
Typing "GET" when OPTIONAL_GUESS_MISSING_NOUN is defined can make the parser print "But you aren't in anyting at the moment.". This is probably because the parser guesses that the player means "GET OUT OF (noun)" and it picks an object we might want to get out of. This may indicate problems in three areas:

1: Maybe the parser should consider "GET (multi)" a better match, since it doesn't require any extra prepositions to complete it.
2: Maybe the parser should print the whole sentence it thinks the player meant to say, to make it clearer, at least if guessing prepositions was required.
3: Maybe the 'get' verb should have its grammar lines in a different order.

One or more of these may require attention.

**Comment by johanberntsson** [comment]
Rewrote parser to prefer shorter patterns as the best guess, which makes the responses better.
