### ISSUE TITLE
Global created before Global.h causes crash in z3

### ISSUE THREAD

**Issue by TechCowboy** [johanberntsson/PunyInform#113]
I'm not sure if this is documented, but if you create a global before the inclusion of global.h will cause 'Fatal Error: Illegal Object'  when creating a z3 file.

```
cd ../PunyInform
pversion=3
../Inform6/inform -d2esi -v$pversion +lib ../COVIX-IX/test.inf
```

![image](https://github.com/johanberntsson/PunyInform/assets/2847372/a09dddcc-13a3-4b65-a425-e62a10946e39)

rename this to test.inf

[test.txt](https://github.com/johanberntsson/PunyInform/files/12524851/test.txt)

**Comment by fredrikr** [comment]
In z3, it may or may not cause a crash, depending on the value of that global.

The correct place to define your own globals is shown in the code skeleton in the manual https://github.com/johanberntsson/PunyInform/wiki/Manual#getting-started , as well as in the minimal.inf file included with the PunyInform distribution. I would say it's well documented.
