### ISSUE TITLE
Document how to generate playable HTML

### ISSUE THREAD

**Issue by dfabulich** [johanberntsson/PunyInform#115]
Almost none of the games in [PunyJam #‍3](https://itch.io/jam/punyjam-3) have "Run Game" buttons on Itch.

IMO, this is because PunyInform doesn't have an easy, documented way of generating an HTML file, suitable for uploading to Itch (or any other website).

Inform 7 has a "[Release along with a website](https://ganelson.github.io/inform-website/book/WI_25_10.html)" feature, and a slimmer "[Release along with an intepreter](https://ganelson.github.io/inform-website/book/WI_25_11.html)" feature (which generates an HTML file based on Parchment).

PunyInform should document how to take a `.z5` file and turn it into an HTML document, suitable for uploading to Itch.

**Comment by johanberntsson** [comment]
Thanks for the pull request.
