### ISSUE TITLE
An unnecessary else statement in MSG_PARSER_NOTHING_TO_VERB

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#121]
```
#IfTrue MSG_PARSER_NOTHING_TO_VERB < 1000;
	MSG_PARSER_NOTHING_TO_VERB:
	! p_arg_1 = the last word in player input + 1.
		if(action == ##Drop or ##Insert && (parse + 2 + (p_arg_1 - 2) *4)-->0 == ALL_WORD) {
			"You are not carrying anything.";
		}  else {
			print "There are no things available that match ~";
			_PrintPartialMatch(verb_wordnum, p_arg_1 - 1);
			"~.";
		}
#EndIf;
```

**Comment by johanberntsson** [comment]
No, the else statement is used in many places and can't be removed.  For example in test1, where the script produces (test1.txt):
> drop cubes
There are no things available that match "drop cubes".

**Comment by johanberntsson** [comment]
I see what you mean, but I tried both with and without the else, and the generated code is exactly the same size. It seems that the compiler is handling this case without problem, and I see no need to change the source code. But thanks for keeping an eye out for possible optimisations.
