### ISSUE TITLE
Unopenable object displayed open with tall inventory 

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#127]
The bucket should not be displayed open with the tall inventory:
```
Object -> bucket "bucket"
    with
        name 'bucket',
    has container open;

Object -> -> water "water"
    with
        name 'water',
        article "some",
    has edible;
```

> ```
> > i wide                                                                                        
> You're carrying a bucket (which contains some water).                                           
>                                                                                                 
> > i tall                                                                                        
> You're carrying:                                                                                
>   a bucket (which is open)                                                                      
>     some water  
> ```

**Comment by fredrikr** [comment]
Fixed. Thanks!
