### ISSUE TITLE
Using creature grammar token

### ISSUE THREAD

**Issue by c64-adventures** [johanberntsson/PunyInform#14]
Hi,

It seems that verb routines in PunyInform don't currently differentiate between animate and inanimate objects when using the creature grammar token.

For example, defining a new verb "Talk":

```
Verb 'talk'
	*	'to'/'with'	creature	-> Talk;

[TalkSub;
	if (noun == player) "The conversation is hardly inspiring.";
	if (RunLife(noun,##Talk) ~= false) return;
	"You have nothing to say.";
];
```

Compiled with PunyInform, this code allows the player to talk to an inanimate object (e.g. > TALK TO CAR) and receive the message "You have nothing to say."

Compiled with the standard Inform libraries, the same code and the same player action returns the message "You can only do that to something animate." In other words, it appears the library is aware that the action has been invoked against an inanimate object and prevents TalkSub from running on that basis.

Should PunyInform act in the same way?

**Comment by johanberntsson** [comment]
Fixed, thanks for the report.

**Comment by johanberntsson** [comment]
As a way of thanking you for the testing and feedback I can add you to the credits. Let me know if you are okay with this, and if c64-adventures is your preferred nick or if I should write something else.

**Comment by c64-adventures** [comment]
Thanks Johan, I've now updated my profile to include my full name. If possible please use that rather than c64-adventures.

Also just want to say that I appreciate the quick responses and fixes from both you and Fredrik on the issues I've raised so far.
