### ISSUE TITLE
Infinite loop when using "PerformAction"

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#17]
I have a house, and I have a door. I want Open, Close, Unlock, and Lock house to be redirected to the door. I write in the house:

before [; Open, Close, Unlock, Lock: PerformAction(action, mydoor);

with 'action' the global that holds the action (because i don't want to change the action, just the noun).

This causes an infinite loop. As far as I can tell:
* PerformAction changes "action" to the first argument, "noun" to the second, and "second" to the third argument
* Then it calls PerformPreparedAction
* This calls BeforeRoutines
* BeforeRoutines checks some stuff, and then (line 631 of puny.h) looks at the before of inp1. But inp1 (input 1?) is the noun that was recognized by the parser - house, not door!

So: can we change "inp1" to "noun" at this point? Or will that break? (I did, and it looks fine, but I'm not 100% sure that I should...) Or should I just never use PerformAction? (But will this be a bug that'll reappear somewhere else?)

**Comment by johanberntsson** [comment]
Thanks. inp1/inp2 were not updated in PerformAction. It should work now. inp1 is usually the same as noun, except for when noun is a number when inp1 will be -1 to show this. See DM4 for more info. Also, you will need to add rtrue; after your call to PerformAction to stop processing in your House object.
