### ISSUE TITLE
Held grammar token

### ISSUE THREAD

**Issue by c64-adventures** [johanberntsson/PunyInform#21]
Hi,

This is similar to issue https://github.com/johanberntsson/PunyInform/issues/14: PunyInform doesn't seem to require that an object specified by `held` in a grammar definition is actually held by the player, as long as it's currently in scope.

The standard Inform 6 library will attempt to pick up the specified in-scope object if the player isn't holding it. If that Take action fails, then the new verb routine (or any associated before routines) will not run. However, PunyInform will proceed with the new action regardless.

**Comment by fredrikr** [comment]
The implicit Take action is not done by the parser, but by the action routines. Thus, some actions may work as expected and others not.

Can you give examples of commands that cause problems?

**Comment by c64-adventures** [comment]
For example, given the following code:

`Object example_room "Example Room"
	with description "You are in an example room, for test purposes.",
	has light;

Object weight "lead weight" example_room
	with name 'lead' 'weight',
		before [;
			Take: print_ret (The) self, " is too heavy to lift.";
	];

Object table "table" example_room
	with name 'table';

[Initialise;
	location = example_room;
];

Verb 'place' 'lean' = 'put';

Extend 'put'
	*	held 'under' noun		-> PutUnder;

[PutUnderSub;
	"You don't see any point in putting ", (the) noun, " there.";
];`

Compiled with the standard Inform 6 library, putting the lead weight under the table causes a Take action first, which is blocked by the weight's before routine:

`Minimal
A sample game which uses PunyInform.
Release 1 / Serial number 200828 / Inform v6.34 Library v6.12.3pre D

Example Room
You are in an example room, for test purposes.

You can see a lead weight and a table here.

>put weight under table
(first taking the lead weight)
The lead weight is too heavy to lift.

>`

If I compile the same code with PunyInform, it assumes the lead weight can be picked up (although this is prevented by its before routine) and runs PutUnderSub:

`Minimal
A sample game which uses PunyInform.
Release 1 / Serial number 200828 / Inform v6.34 PunyInform v1.5

Example Room
You are in an example room, for test purposes.

You can see a lead weight and a table here.

> put weight under table
You don't see any point in putting the lead weight there.

>`

This wouldn't be an issue if I had defined PutUnder as

`Extend 'put'
	*	noun 'under' noun		-> PutUnder;`

because then there is no expectation that the player needs to be holding the object they want to put under the second object.

**Comment by c64-adventures** [comment]
Or, if I replace the PutUnderSub code with something less likely:

```
[PutUnderSub;
	remove noun;
	"You put ", (the) noun, " under ", (the) second, ".^^", (The) noun, " suddenly vanishes!";
];
```
Then the standard Inform library and PunyInform now act in very different ways:

Standard:
```
Minimal
A sample game which uses PunyInform.
Release 1 / Serial number 200828 / Inform v6.34 Library v6.12.3pre D

Example Room
You are in an example room, for test purposes.

You can see a lead weight and a table here.

>put weight under table
(first taking the lead weight)
The lead weight is too heavy to lift.

>
```
PunyInform:
```
Minimal
A sample game which uses PunyInform.
Release 1 / Serial number 200828 / Inform v6.34 PunyInform v1.5

Example Room
You are in an example room, for test purposes.

You can see a lead weight and a table here.

> put weight under table
You put the lead weight under the table.

The lead weight suddenly vanishes!

>
```

**Comment by johanberntsson** [comment]
Thanks for the report. I didn't check the implicit take result properly, now fixed. I added a unit test with your example code so we won't see this problem in the future.
