### ISSUE TITLE
sw_to affects debug verbs

### ISSUE THREAD

**Issue by c64-adventures** [johanberntsson/PunyInform#22]
Hi,

This is a strange one, but easy to replicate. If I enable debugging, then define a sw_to room exit anywhere in my code, any debug verb that takes a noun (e.g. gonear, purloin) fails with the following response:
```
> purloin table
I only understood you as far as "purloin table" but then you lost me.
```
Amending the sw_to to any other direction and recompiling fixes the debug verb behaviour.

**Comment by fredrikr** [comment]
Great finding.

This was due to parse_name being an alias for sw_to. Should work perfectly in pretty much all cases now.
