### ISSUE TITLE
Status line doesn't update

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#23]
Not sure this is a puny bug, but...

Several interpreters do not update the status line, or show the wrong thing, or garbage. This includes Edilbert Kirk's VIC-20 interpreter (showing garbage in the name of the room), Fabularium (no room shown, no update for score and turns) and ZXZVM for Spectrum & CPC (no room shown, no update for score and turns). If it was a problem happening on only one terp I'd say it's a terp bug, but...
Any idea what's happening?

**Comment by fredrikr** [comment]
I would guess that this is a z3 game and that you define one or more global variables before including globals.h. This will cause the statusline to fail in multiple ways on all interpreters.

**Comment by hlabrand** [comment]
Oh wow, that's exactly it! Thank you so much, I wouldn't have guessed. (Would it be possible to add this behavior to the manual, section "z3 limitations"?)

**Comment by fredrikr** [comment]
We could make the basic structure of a PunyInform game file clearer. Place your globals after including globals.h.

And of course, this is the same if you use Metrocenter'84 or the early versions of the Inform library which could compile to z3.
