### ISSUE TITLE
"_LookForLightInObj" and open containers

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#26]
The condition to look for light is "if(p_obj == p_ceiling || p_obj has transparent || p_obj has supporter || (p_obj has container && p_obj has open))"

If I'm not mistaken, an open container is something that can receive objects but not automatically list them (in the description, for instance - you have to look inside). For instance, a backpack.
If you want the object list to be displayed, you have to give it "transparent". Additionally, I believe that "transparent" is also a condition adding the contents to the scope.

So:
- putting a flashlight in an empty fish bowl should still give off light: "p_obj has transparent" should be a condition that's accepted (if it's good enough for the scope...)
- if I put my flashlight in an open backpack, should the room still be lit? I.e. should it be "open and transparent", or "open or transparent"

**Comment by hlabrand** [comment]
Never mind, just noticed the "p_obj has transparent" at the beginning. The conditions for the scope are in a different order, which threw me off. Sorry!

**Comment by fredrikr** [comment]
Contents are automatically listed if you can see them, except if the container's description is printed by a special routine during the Look command (like initial, when_open, when_on etc). If so, the object will need to print its own contents. Look in the howto-folder for an example of how to do this.
