### ISSUE TITLE
vehicle_mode

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#30]
DM4 page 128: "If a player is inside an enterable object and tries to move, the before of the parent is called with <Go dir>, and can return 0 (disallow and print no), 1 (allow but move the vehicle with), 2 (silently disallow), 3 (silently allow)".
This is in verblibm.h, line 1805: run the routine "before", if k isn't 3 restore the location to the original one, if k isn't 1 rtrue (if it is 1 keep going, you and the vehicle will get moved).

Puny doesn't differentiate between 2 and 3. The only difference in Inform's code is that Inform saves the location (j=location), then restores it (location=j) if the answer of the before is 2. That's a bit confusing; but i guess it's to prevent people from changing location and then returning 2? (But why would you change the location if you're planning on printing 2??)

I'm having a hard time following Inform's logic here, so maybe I'm missing something. But maybe Puny should rephrase the comment on line 1607 of grammar.h, to emphasize "contrary to inform, we treat 2 and 3 the same, so don't change the location if you return 2 please". Or change the code to match Inform's logic (whatever it is).

**Comment by johanberntsson** [comment]
I6 saves the location because location is set to real_location if we are in darkness before calling the before-routine, so that it may check the correct location. I've changed the logic to match I6.
