### ISSUE TITLE
"Sometimes meta" verbs

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#31]
Some verbs can be tagged as "meta" in their declaration (that is, they don't increase the turn counter).
Sometimes, some way to use the verb is meta, and some other isn't. ("Restart vs Restart generators" is the case I have, there's also "about vs about face", or in French "quitter vs quitter robe" (quit vs disrobe))

The standard from I6 is to use a GPR and turn on "meta" during the parsing, as at the end of this page: http://www.firthworks.com/roger/informfaq/vv.html

In puny, this doesn't work; I get "I think you wanted to say 'restart something'" when I try to restart. Is it a puny bug, or is there another way?

My code is this btw:
[ isMeta; meta = true; return GPR_PREPOSITION; ];
Extend 'restart' replace
* isMeta                ->Restart
* noun                  ->SwitchOn; ! restart generator

**Comment by johanberntsson** [comment]
I fixed a bug and it works. See an example is tests/test6.inf. But note that then you extend/replace a verb that is already defined as meta then you have to invest the logic and use a parser routine to turn off the meta flag when needed. It works the same in I6.
