### ISSUE TITLE
"What is"-verb in "Library of Horror" not working in v1.6 and v1.7

### ISSUE THREAD

**Issue by kpeamon** [johanberntsson/PunyInform#32]
_EDIT: The "What is"-verb works in v1.5 and older but not in v1.6 and v1.7. I don't know if the game has been updated or only PunyInform, but if I try to compile the inf-file from v1.7 with PunyInform v1.5 then the verb "What is" works also._

I am very interested in how to implement something similar to the verb "What is" in the demo-game "Library of Horrors". But before looking at the code, I would like to have an idea of how the game actually responds to the "what is"-verb. Thus I compiled the game and tried these topics as soon as the game started:

**what is library**
You haven't the faintest.

**what is grue**
You haven't the faintest.

**what is manager**
You haven't the faintest.

**what is a library**
You haven't the faintest.

**what is the library**
You haven't the faintest.`

From the code I can see, that the game has responses to these 3 topics, but nothing works.

The code:
		**_topics
			1 'library' "A library is venue where books are kept and people can borrow said books."
			1 'grue' "A grue is a sinister creature lurking in the dark. If anyone has actually seen a grue,
				they have not lived long enough to tell the tale."
			1 'manager' "Library managers oversee the daily activities and functions of a library.";_**

So I have the impression that the "What is"-verb is not working as intended.
Thanks

**Comment by johanberntsson** [comment]
Thanks, I fixed the bug. tests/test6.inf now contains a working 'what' verb implementation.
