### ISSUE TITLE
"noun=Routine" tokens are incorrectly displayed in _FixIncompleteSentenceOrComplain

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#33]
Consider the following verb definition with a general parsing routine to create a new token:

[NotHeld;
   if(noun in player || noun == 0) {rfalse;} else {rtrue;}
];
Verb 'steal'
* noun=NotHeld ->Take;

If a player types "steal", the message is "I think you wanted to say steal (random garbage)". The garbage happens on line 1108 of parser.h, when trying to print whatever is at the address.
If I write "*noun ->Take" it's correct ("I think you wanted to say steal something")

Could the fact that it's a routine be detected, and in that case treat it like a noun, i.e. print "something"? (Only "noun=Routine" is allowed by the I6 compiler.)

**Comment by johanberntsson** [comment]
Thanks, fixed.
