### ISSUE TITLE
Make darkness and carrying capacity optional

### ISSUE THREAD

**Issue by hannessssss** [johanberntsson/PunyInform#38]
Not an issue per se, but a proposal/feature request. I think only a miniscule number of games use these mechanics. First thing I always do in a new project is define a Room class with "has light" in order not to be further bothered by this. I see that both may have their specific uses, but in general, they can be considered a waste of space.

**Comment by johanberntsson** [comment]
Thanks for the suggestion. We need to discuss this. Moved to a new ticket in Trello for future consideration:
https://trello.com/c/gGsOq2BS/181-make-darkness-and-carrying-capacity-optional-hannessssss-not-an-issue-per-se-but-a-proposal-feature-request-i-think-only-a-minis

**Comment by fredrikr** [comment]
Darkness is now optional. Define OPTIONAL_NO_DARKNESS to get rid of darkness handling. This saves 340 bytes.

**Comment by fredrikr** [comment]
Oops, it saves 360 bytes.
