### ISSUE TITLE
GrabIfNotHeld

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#40]
This function (defined in parser.h) ends in "if(p_noun notin player) rtrue;". But a lot of places that use it (1 in parser, 3 in grammar) call it (_GrabIfNotHeld(noun)) then check "if noun notin player".

(I tried to fix it quickly but it broke my game. I'm hoping someone with better unit tests will be able to fix it :D)

**Comment by johanberntsson** [comment]
No place seems to use the return value, so the if-statement seems redundant, but is it wrong? Can you give me an example of where using _GrabIfNotHeld seems to go wrong. What is there to fix?

**Comment by hlabrand** [comment]
No it's not a bug, it's just that you're returning a value and then recomputing it. It could be "if (_GrabIfNotHeld(noun)) rtrue;"

**Comment by johanberntsson** [comment]
Yeah, make sense. I've added unit tests and changed the logic as you suggested.
