### ISSUE TITLE
Can't override SEARCH action with Cheap_Scenery SceneReply

### ISSUE THREAD

**Issue by ByteProject** [johanberntsson/PunyInform#41]
Cheap scenery is very flexible in providing a way to let authors define scenery related replies via SceneReply.

Today I've created a SceneReply for the SEARCH action. But it did not work and that drove me crazy. Turns out (after investigating Cheap_Scenery's code) that you can define custom replies for every action except EXAMINE, which makes sense of course, and *drumroll* SEARCH, which I don't think makes sense. There is no use in preventing the author from defining a custom message here and the result, as it is now, is that you get the default "You find nothing special." reply. Just by taking out SEARCH from Cheap_Scenery's  before [; routine you get two effects: 1) the standard "No need to concern yourself with that." message for scenery is being triggered if the author had chosen to not override SEARCH. 2) The author is able to define an own statement, for example like "There is no need searching this.". The code that would be subject for deletion is highlighted in the screenshot below.

![image](https://user-images.githubusercontent.com/153544/99317939-1f7d9b00-2867-11eb-9b3e-dfafb7991c04.png)

**Comment by fredrikr** [comment]
![image](https://user-images.githubusercontent.com/1001548/99386966-7f119000-28d3-11eb-8254-97efc1a8a828.png)
