### ISSUE TITLE
Timers out of sync when manually advancing turn count

### ISSUE THREAD

**Issue by hannessssss** [johanberntsson/PunyInform#42]
Maybe I'm approaching this in a fundamentally wrong way...

I have several timers running to trigger events. They work exactly on spot when playing normally. However, I also have a SLEEP action which advances time significantly. I'm doing this by manually increasing turn count:

turns = turns + 50;

This works fine as far as the turn count itself is concerned. However, for the purpose of timers, the SLEEP action only advanced the time_left by one, i.e. it does not heed/notice the jump in turn count.

I can work around this by stopping the timer and restarting it with a manually recalculated timeout. Though I'm wondering if this is intended behaviour.

**Comment by fredrikr** [comment]
The timers and daemons mechanism doesn't care about the turn counter.

If you want timers and daemons to run for each turn as you advance the turn counter in your sleep action, you need to run them yourself. Something like:

```
while(i++<50 && deadflag == GS_PLAYING) {
    turns++;
    RunTimersAndDaemons();
}
```

**Comment by hannessssss** [comment]
While you may not consider this a bug (fair enough), don't you think it would be worth documenting at least? Timers in their basic form (start/stop syntax) are associated with turn count directly. So this behaviour is very likely to go against game author expectations.

**Comment by fredrikr** [comment]
The turn counter is something you can't just change and expect the library to figure out what you mean, just like you can't move the player except for with the PlayerTo routine. 

A wait or sleep command that spans several moves typically needs a bit more work anyway - if a daemon makes a person enter the room, or a gunshot is heard, you may want to give the player the chance to abort the waiting and spring to action. Also, you probably want the statusline to reflect the time or moves, even as you wait. There are extensions for Inform 6, like waittime.h, that handles these things.

To make it easier to create a WAIT command, we have now placed the code executed at the end of the turn in a routine called EndTurnSequence. This  can be called by the WAIT command to run timers and daemons, each_turn, advance time/turns and update darkness. It's a public routine and we will mention it in the manual.

**Comment by hannessssss** [comment]
Hm, I thnk it's fairly obvious what a game author intends if turn count is manually manipulated: all derived logic (meaning time, daemons and timers) should adapt. Don't think this is a weird expectation at all. Though if I understand correctly what you describe, this would enable to more easily adapt such behaviour in the game code, so thank you!

**Comment by fredrikr** [comment]
There is now a new extension called ext_waittime.h which provides a more advanced Wait verb.
