### ISSUE TITLE
Return value for switchable objects. 

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#43]
There have been some changes in library 6.12 regarding switchable objects, and it seems to me that it's better that way:
https://gitlab.com/DavidGriffith/inform6lib/-/commit/6055afbfecc46f971c7dd626d4267c8be60f6eda
```
Object torch "torch" Library
with
   name 'torch',
	description "It's torch.",
has switchable;
```
Inform 6.12:
> x torch
It's torch.

PunyInform:
> x torch
It's torch.
The torch is currently switched off.

**Comment by auraes** [comment]
```
Object room1 "room1" with description "Room1" has light;

Object torch1 "torch1" room1
with
   name 'torch1',
	description "It's torch1."
has switchable;

Object torch2 "torch2" room1
with
   name 'torch2',
	description [; print "It's a torch2.^"; ],
has switchable;

Object torch3 "torch3" room1
with
   name 'torch3',
	description [; rfalse; ]
has switchable;
```
Inform 6.12:
>\>x torch1
It's torch1.

>\>x torch2
It's a torch2.
The torch2 is currently switched off.

>\>x torch3
The torch3 is currently switched off.

PunyInform:
>\> x torch1
It's torch1.
The torch1 is currently switched off.

> \>x torch2
It's torch1.
The torch1 is currently switched off.

>\>x torch3
It's torch1.
The torch1 is currently switched off.

**Comment by fredrikr** [comment]
Good suggestion. Changed.
