### ISSUE TITLE
Maybe an extra space?

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#45]
I don't know if this is done on purpose, but when displaying `"*** You have won.  ***"`, there are two spaces before the final stars: `"won []***"`.

**Comment by auraes** [comment]
This also seems to be the case for the following messages after the end point, but there may be a good reason for this:
```
 MSG_SWITCH_ON_ON, MSG_SWITCH_OFF_NOT_ON:
  print_ret (CTheyreorThats) noun, " already ", (OnOff) noun, ". ";
 MSG_SWITCH_ON_SUCCESS, MSG_SWITCH_OFF_SUCCESS:
  "You switch ", (the) noun, " ", (OnOff) noun, ". ";
```

**Comment by fredrikr** [comment]
Fixed.
