### ISSUE TITLE
An object with the scenery attribute in the inventory bugs its display

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#48]
Let me know if you don't want to hear about this kind of bug whose initial state is illegal.
```
Object apple "apple" SelfObj
 with
  name 'apple',
  description "it's an invisible apple.",
 has scenery;
```
```
The Library
You are in a library.

> i

> 
```

**Comment by fredrikr** [comment]
As you say, this can only happen due to a bug in a game author's code - a scenery object should never end up in the possession of the player.

Fixing it would make the library bigger. I think we'll leave it the way it is.
