### ISSUE TITLE
Order of the directions

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#5]
I'm trying to devise some compact code to get around in a series of room so that I only have to code one room + reactions to directions. There's a little something that makes this annoying in Puny.

I'm trying to go from selected_direction to FAKE_*_OBJ.
If I read "selected_direction-N_TO_CONST+FAKE_N_OBJ", I get : "N=10001, S=10002, E=10003, W=10004, NE=10005, NW=10007, SE=10006, SW=10008"
This is different from the definitions in globals.h, where NW = 10006 and SE = 10007. This is because the direction properties (line 134) are defined in a different order (N S E W NE SE NW SW) than the FAKE_*_OBJ (N S E W NE NW SE SW).

Switching the value of the constants FAKE_NW_OBJ and FAKE_SE_OBJ would make it so one can go from "selected_direction" to "FAKE_N_OBJ" and back very easily, which would be good.
Furthermore I feel like you rely on this kind of arithmetic elsewhere (puny.h : lines 697 to 722), which, if I'm not mistaken, means that Puny switches Southeast and Northwest in these functions - definitely a bug.

Thanks!

**Comment by fredrikr** [comment]
Thanks for pointing this out! This was of course a mistake. Have fixed it now.

Note: The routines which you point out in Puny.h are also mentioned in the manual - calling these routines is the "official" way of translating between direction properties and fake direction objects.
