### ISSUE TITLE
Ensure that objects in open/transparent container scenery are described. 

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#50]
Everything is here:
https://gitlab.com/DavidGriffith/inform6lib/-/commit/7fbac4d4a2b67dcbb4f524a62ac1b0b6e58a3959

**Comment by fredrikr** [comment]
PunyInform doesn't print the contents of either supporters or containers which have scenery or concealed. We can see how some authors might want it to, so we have new added a constant OPTIONAL_PRINT_SCENERY_CONTENTS which, if defined, makes the library print these contents.

For the future, please describe to us what changes you'd like to see in Puny, not just a link to an issue somewhere else.
