### ISSUE TITLE
Menu titles are not centered correctly

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#55]
In the ext_menu.h extension, the centering calculation of the menu titles seems to be wrong:
`j=1+(i/2-main_wid)*cw; j=1+(i/2-item_width)*cw;`
This seems more correct:
`j=1+((i-main_wid)/2)*cw; j=1+((i-item_width)/2)*cw;`

And 'cw' being initialized to 1, multiplication and so on are of little use.

**Comment by fredrikr** [comment]
Approved. Thanks!
