### ISSUE TITLE
n_to, etc executed when entering a room

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#6]
The code attached has different behavior in Puny and I6libs. Puny executes all the directions upon entering the new room when these directions are routines. (I'd like these to be able to be routines, in order to create interesting behavior without copy-pasting code. Didn't see anything in the manual that prohibits this behavior...)
My intuition is that Puny stores these somewhere when entering a new room, but doesn't check whether they are routines or not.

Code :

[ Move ;
    print "Hahaha nope^"; rtrue;
];

Object loc "Test room"
  with description "This is a test",
  s_to loc2,
has ;

Object loc2 "Test room 2"
  with description "",
  n_to Move,
  s_to Move,
  e_to Move,
has ;

**Comment by fredrikr** [comment]
I can't reproduce the problem. I tried this as a z3 with Puny and as a z8 with standard lib. The only change was that I added "has light" to the rooms. This is a transcript, and it's identical for the two:

Test room
This is a test

> s

Test room 2


> s
Hahaha nope

> n
Hahaha nope

> e
Hahaha nope

> w
You can't go that way.

> s
Hahaha nope

>

**Comment by hlabrand** [comment]
Sorry! I thought I had isolated the problem but obviously not. (I think I forgot there were classes involved.) Here's a file that definitely doesn't work
[tristam.txt](https://github.com/johanberntsson/PunyInform/files/4962882/tristam.txt)

**Comment by fredrikr** [comment]
Thanks for your help. Fixed.
