### ISSUE TITLE
Parser misinterprets get/drop command followed by multiple sentences containing directions

### ISSUE THREAD

**Issue by c64-adventures** [johanberntsson/PunyInform#60]
Hi,

If the player tries to get or drop an item, followed by a series of movement commands, with the get/drop item command and movement commands all on one line, separated by full stops, then each movement command seems to be misinterpreted by PunyInform as a request to either get or drop the last direction in the sequence, instead of moving in the specified direction.

For example:

```
Minimal
A sample game which uses PunyInform.
Release 1 / Serial number 210110 / Inform v6.34 PunyInform v1.8 D

Example Room
You are in an example room, for test purposes. A similar-looking room lies to the west.

You can see a lead weight here.

> get weight.w.e
lead weight: Taken.
east: That's hardly portable.
east: That's hardly portable.

> 
```

If the subsequent movement commands are in the form (e.g.) GO NORTH rather than N or NORTH, everything works as expected:

```
Minimal
A sample game which uses PunyInform.
Release 1 / Serial number 210110 / Inform v6.34 PunyInform v1.8 D

Example Room
You are in an example room, for test purposes. A similar-looking room lies to the west.

You can see a lead weight here.

> get weight. go west. go east
Taken.


Another Example Room
You are in another example room, again for test purposes. The other example room is east.


Example Room

>
```

(Side note: it actually looks like there's an additional newline between each location in the above output, compared with how the standard I6 library outputs the same code. I can raise that as a separate issue if it's a bug rather than design.)

**Comment by johanberntsson** [comment]
Thanks, fixed.

**Comment by c64-adventures** [comment]
Thanks for looking at this. This is what happens now with the same code and actions:

```
Example Room
You are in an example room, for test purposes. A similar-looking room lies to the west.

You can see a lead weight here.

> get weight.w.e
Taken.

I only understood you as far as "w" but then you lost me.

> 
```

So there seems to still be an issue somewhere, unfortunately.

**Comment by johanberntsson** [comment]
Fix one thing and break another... 'get weight.w' worked, but not 'w.e'. Now it has been fixed (again) and I've added both patterns to the unit tests so that it won't happen again. Thanks for testing and reporting.
