### ISSUE TITLE
Priority of MSG_TAKE_SCENERY and MSG_TAKE_STATIC messages for the action Take. 

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#61]
For Pull, Push and Turn actions the static attribute has priority over the scenery attribute, but not for the Take action. It seems more interesting to me to keep the priority of the static attribute over the scenery attribute although the current behavior is consistent with that of the standard Inform 6 library.
```
[ PullSub;
   ...
	if (noun has static)   { PrintMsg(MSG_PULL_STATIC); rtrue; }
	if (noun has scenery)  { PrintMsg(MSG_PULL_SCENERY); rtrue; }
];
[ PushSub;
   ...
	if (noun has static)   { PrintMsg(MSG_PUSH_STATIC); rtrue; }
	if (noun has scenery)  { PrintMsg(MSG_PUSH_SCENERY); rtrue; }
];
[ TurnSub;
	...
	if (noun has static)   { PrintMsg(MSG_TURN_STATIC); rtrue; }
	if (noun has scenery)  { PrintMsg(MSG_TURN_SCENERY); rtrue; }
];

The attribute scenery has priority here:
[ TryToTakeNoun _i _k _ancestor _after_recipient;
   ...
   if(noun has scenery) { PrintMsg(MSG_TAKE_SCENERY); rtrue; }
   if(noun has static) { PrintMsg(MSG_TAKE_STATIC); rtrue; }
];

```

**Comment by fredrikr** [comment]
We think it makes sense the way it is. Push, pull and turn are actions whose only purpose is to move (as in shift the position or orientation of) the object, and if the object is static, that's really the primary concern. The take action has the objective of holding the object (which involves moving it, but that's not the primary point of the action), and one could argue that the scenery attribute is more important in this case.
