### ISSUE TITLE
Completely disable the Score/Turns display for version 5

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#62]
Comment "Constant STATUSLINE_SCORE; Statusline score;" does not disable Score/Turns display for version 5. What is the difference with or without this constant, and how to disable Score/Turns display for version 5?

**Comment by fredrikr** [comment]
It's not supposed to disable Score/Turns display at all. It's supposed to show Score/Turns.

The constant is there to remove code which is only needed for games showing Time on statusline, to help keep the code size down.

There is currently no option to disable Score/Turns display.

**Comment by auraes** [comment]
The documentation is a bit confusing:   
"To show score and turns in the status line, put Constant STATUSLINE_SCORE; Statusline score; in the beginning of the source."  
I deduce that if I don't want to display Score/Turns, I don't put the constant!

**Comment by fredrikr** [comment]
Ah sorry. It's either Score/Turns or Time. If you don't do anything you get Score/Turns, but the code to display Time will still be compiled, wasting space.

Will improve docs.

**Comment by fredrikr** [comment]
I have improved the documentation.
