### ISSUE TITLE
Make whitespace before room description customizable

### ISSUE THREAD

**Issue by ByteProject** [johanberntsson/PunyInform#66]
A recent change in Puny causes the library to not print a newline before a new room description is shown on screen, which is on-par with what Infocom did back in the day. Previously, Puny behaved like Inform, where a newline is printed before a new room description is shown. A formatting I relied on. For me this means now that I either need to override _[New Room;]_ to get the old behavior again, or I would need to work through all the code of my two current Puny projects and check where the new formatting results in text printed unproperly formatted on screen. Just with a quick test I have noticed it is an issue for every spot where I was _return location;_ 

My request would be making this option customizable so one can decide which formatting is applied.

**Comment by johanberntsson** [comment]
You will be happy to know that I've added MSG_LOOK_BEFORE_ROOMNAME which can be used to restore the old behaviour. Just add 
Constant MSG_LOOK_BEFORE_ROOMNAME 1003;
[LibraryMessages p_msg p_arg_1 p_arg_2;
    switch(p_msg) {
    MSG_LOOK_BEFORE_ROOMNAME:
        @new_line;
    }
    p_arg_1 = 0; p_arg_2 = 0; ! To avoid warnings
];
before
Include "puny.h";

**Comment by ByteProject** [comment]
Amazing, thanks for that!
