### ISSUE TITLE
Status line doesn't print the short_name if inherited

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#7]
I defined a class of objects all with the same short_name (very useful to factor code in, e.g.,  a maze). However, the name that is written in the status line is not the right one; instead, it's the name of the room in brackets, as if short_name was empty. The I6 library doesn't have trouble with it. File is attached (same as issue 6)
[tristam.txt](https://github.com/johanberntsson/PunyInform/files/4962890/tristam.txt)

**Comment by fredrikr** [comment]
This is a limitation of the z3 format, and there is absolutely no way around it.

Inform 6 standard library handles it, simply because it doesn't compile to z3. Compiling to z5 using PunyInform works equally well.

**Comment by fredrikr** [comment]
I added a note about this in the manual section on limitations of the z3 format. 

Thanks for pointing it out. It's not obvious.
