### ISSUE TITLE
Inappropriate message when trying to put an absent object in a container object

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#75]
When you try to put an object that exists, but is not in the scope, the message seems inapropriate:
>\> put apple in box                                             
I only understood you as far as "put" but then you lost me.  

Perhaps "**You can't see any such thing.**" would be more appropriate.  
```
Object Library "The Library"
	with description "You are in a library.";
Object -> Box "box"
	with name 'box',
	has container open openable;
Object apple "apple"
	with name 'apple',
	has edible;
```

**Comment by johanberntsson** [comment]
Thanks, changed as you suggested.
