### ISSUE TITLE
Add "yell" / allow "shout" without noun

### ISSUE THREAD

**Issue by Kroc** [johanberntsson/PunyInform#80]
It's not possible to "shout" at nothing in particular. There's a few situations where this is possible:

* The player is testing their senses; let's say they can't see right now.
  They can "smell" and "listen" but can't "speak"/"shout" when nothing can be seen
* Useful for simulating an echo
* Being able to shout in a room that contains multiple things that can react to sound
* "Yell", "Shout" & "Scream" are fairly obvious verbs and yet aren't in the library

**Comment by fredrikr** [comment]
Added in PunyInform v2.6. "speak" still can't be used without a target as we're afraid this will disguise the fact that you need to give a target to address someone. A game can of course alter this behaviour quote easily.
