### ISSUE TITLE
"Again" followed by further text

### ISSUE THREAD

**Issue by c64-adventures** [johanberntsson/PunyInform#81]
If the player enters "again"/"z" followed by another further text, PunyInform responds in a different way to the standard library.

In PunyInform:

```
> again me
You can't see any such thing.
You can hardly repeat that.
```

Whereas with the standard library:

```
>again me
You can hardly repeat that.
```

**Comment by johanberntsson** [comment]
Thanks for the report. Fixed in trunk.
