### ISSUE TITLE
Warnings when compiling stuff in test/

### ISSUE THREAD

**Issue by DavidGriffith** [johanberntsson/PunyInform#83]
Several of the programs in `test/` and `testbench.inf` throw warnings when being compiled.

**Comment by johanberntsson** [comment]
Yes, that's true. Mostly warning for unused constants etc. We are mainly interested in if it compiles and produces the correct test result when developing Puny, so this has had low priority. Is it a problem for you/Inform? It can of course be fixed.

**Comment by DavidGriffith** [comment]
I suppose I could fix them myself and submit a pull request.  My main concern is about people filing bugs over at https://gitlab.com/DavidGriffith/inform6unix/ about the warnings.

**Comment by johanberntsson** [comment]
You don't have to do that. I'll fix it, but it will have to wait until tomorrow. If you feel it is urgent I'll of course accept a pull request instead, but otherwise I'm on it.

**Comment by johanberntsson** [comment]
All done!
