### ISSUE TITLE
Debug verbs not recognising objects

### ISSUE THREAD

**Issue by c64-adventures** [johanberntsson/PunyInform#84]
Hi,

It seems that if a game object doesn't have a parent, and provides a parse_name routine instead of a name property, then the debug commands that relate to objects don't recognise it. In other words, it can't be purloined or its object tree displayed,

As long as the object has a parent (even if the parent object doesn't have a parent itself, and it also provides a parse_name routine instead of a name property), the debug commands can interact with it without issue.

**Comment by fredrikr** [comment]
Yes. https://github.com/johanberntsson/PunyInform/wiki/Manual#debugparsenameobject
