### ISSUE TITLE
Punyform V3 not compiling a project on ubuntu 20.04 with Inform6.34

### ISSUE THREAD

**Issue by shifters67** [johanberntsson/PunyInform#86]
Just trying to build the sample library_of_horror.inf with 

./inform6 -v3 +lib library_of_horror.inf

and it fails with 

Compiling to z3 format
Inform 6.34 for Unix (21st May 2020)
"lib/messages.h", line 645: Error:  Expected switch value but found #
> #Ifndef
Compiled with 1 error (no output)

Same happens when trying to compile a v5 version also.

I downloaded the source for Inform6.35 as there is only a binary for windows and used the 6.34 project layout as the 6.35 source does not have the code to build it in the tgz file for unix.

Retried compiling with 6.35 and it works fine.

shifters

**Comment by johanberntsson** [comment]
I'm sorry, we forgot to update the requirements in the documentation. PunyInform now requires at least Inform v6.35. It may take some time before Ubuntu updates its packages, but Inform is easy to recompile from source on Linux. The latest releases can be found at https://github.com/DavidKinder/Inform6

**Comment by fredrikr** [comment]
Another option to consider is David Griffith's Inform package for Unix: https://gitlab.com/DavidGriffith/inform6unix . If doesn't have PunyInform v3.0 yet, but you can just extract PunyInform v3.0 in the PunyInform folder after installation, overwriting the files.
