### ISSUE TITLE
Compiling example .inf files on ubuntu 20.04 fails

### ISSUE THREAD

**Issue by shifters67** [johanberntsson/PunyInform#9]
Hi,

following the site instructions to install punyinform and compile the example .inf files e.g. minimal.inf, nada.inf or library_of_horror.inf results in errors (all the same) - see below.  I suspect i am doing something wrong but i can't see what.

The version of inform 6.34 was compiled from the source linked from your information page.

Any ideas?

./inform6 +lib -v3 -s -e library_of_horror.inf
Inform 6.34 for Unix (16th August 2017)
"lib/globals.h", line 242: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array abbr_direction_array static
"lib/globals.h", line 242: Error:  Expected ';' but found Array
> Array
"lib/globals.h", line 243: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array full_direction_array static
"lib/globals.h", line 243: Error:  Expected ';' but found Array
> Array
"lib/globals.h", line 244: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array direction_properties_array static
"lib/globals.h", line 244: Error:  Expected ';' but found Array
> Array
"lib/globals.h", line 245: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array direction_name_array static
"lib/globals.h", line 245: Error:  Expected ';' but found #
> #
"lib/globals.h", line 248: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array _dir_start static
"lib/globals.h", line 248: Error:  Expected ';' but found Array
> Array
"lib/globals.h", line 249: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array _dir_end static
"lib/globals.h", line 249: Error:  Expected ';' but found #
> #
"lib/ext_flags.h", line 35: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array flag_powers static
"lib/ext_flags.h", line 35: Error:  Expected ';' but found Array
> Array
line 231: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array quote_stairs static
line 231: Error:  Expected ';' but found Array
> Array
line 245: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array quote_darkchamber static
line 245: Error:  Expected ';' but found Include
> Include
line 871: Error:  Expected '->', '-->', 'string', 'table' or 'buffer' but found static
> Array opposite_directions static
line 871: Error:  Expected ';' but found #
> #
"<veneer routine 'RV__Pr'>", line 1: Error:  A function may be called with at most 3 arguments
> "read", obj, identifier, 2);
In: 10 source code files              5534 syntactic lines
  8217 textual lines                218165 characters (ISO 8859-1 Latin1)
Allocated:
   831 symbols (maximum 10000)     1032655 bytes of memory
Out:   Version 3 "Standard" story file 2.200802 (34.5K long):
     5 classes (maximum  64)            27 objects (maximum 255)
    64 global vars (maximum 233)      1250 variable/array space (maximum 10000)
    63 verbs (maximum 200)             228 dictionary entries (maximum 2000)
   124 grammar lines (version 2)       234 grammar tokens (unlimited)
    68 actions (maximum 200)            29 attributes (maximum 32)
    27 common props (maximum 30)        11 individual props (unlimited)
 18762 bytes of Z-code                 214 unused bytes stripped out (1.1%)
 19462 characters used in text       12458 bytes compressed (rate 0.640)
    64 abbreviations (maximum 64)      245 routines (unlimited)
  4381 instructions of Z-code         2692 sequence points
  6310 bytes readable memory used (maximum 65536)
 35130 bytes used in Z-machine       95942 bytes free in Z-machine
Compiled with 21 errors (no output)
Completed in 0 seconds

cheers

shifters

**Comment by fredrikr** [comment]
If you look at the package you downloaded it says it contains a pre-release version of Inform 6.34, and the filedate is in 2018.

PunyInform requires the final version of Inform 6.34 which was released in 2020. You can use the package you have, but replace the Inform source code files with the ones you find in inform634_source.zip at https://www.ifarchive.org/indexes/if-archive/infocom/compilers/inform6/source/ and 'make' again.

David Kinder is working on updating this package. I'm hoping it will be done within a week or so.
