### ISSUE TITLE
"Again" regression?

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#90]
There seems to be a problem with "again"/"g" in the latest version of the code:
- it works for actions without nouns, like "swim" ;
- it doesn't work for actions with nouns, like "x boulder". To clarify: the action doesn't move any objects, the full action always works, typing "again" always fails with "You can't see any such thing.".

Thanks!

**Comment by johanberntsson** [comment]
It was a side effect from a fix yesterday, which I didn't have test coverage of. Well spotted! Fixed, and tests added to make sure that again and oops work in the future as well.
