### ISSUE TITLE
ThatorThose logic error

### ISSUE THREAD

**Issue by hlabrand** [johanberntsson/PunyInform#91]
The "ThatorThose" routine is used in "you can't set that/those". Its code is as follows:
```
[ ThatorThose obj;
	if (obj has pluralname || obj == player) print "those"; else print "that";
];

```
This means that "set me to 100" would in theory reply "you can't set those" instead of "that".
(I think this code was copy-pasted from "is or are" without being adapted)

**Comment by johanberntsson** [comment]
Thanks, fixed.
