### ISSUE TITLE
Reversed definition of MSG_THROW_ANIMATE and MSG_THROW_DEFAULT constants

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#98]
There is a semantic problem in ThrowAtSub():
`if(second hasnt animate) { PrintMsg(MSG_THROW_ANIMATE); rtrue; }`
If the object does not have the animate attribute, there is no reason to display the message MSG_THROW_ANIMATE.

It seems that this would be more correct:
```
#Ifndef MSG_THROW_ANIMATE;
Constant MSG_THROW_ANIMATE "You lack the nerve when it comes to the crucial moment.";
#Endif;
#Ifndef MSG_THROW_DEFAULT;
Constant MSG_THROW_DEFAULT  "Futile.";
#Endif;

[ ThrowAtSub;
        ...
	if(second hasnt animate) { PrintMsg(MSG_THROW_DEFAULT); rtrue; }
	if(RunLife(second,##ThrowAt) ~= 0) rfalse;
	PrintMsg(MSG_THROW_ANIMATE);
];
```

**Comment by auraes** [comment]
I may be wrong because by default the grammar considers that you throw something to someone. So in this case naming the constant MSG_THROW_DEFAULT seems coherent. It is the naming of MSG_THROW_ANIMATE that is confusing.

**Comment by johanberntsson** [comment]
Constants have to be kept reasonably short, and I think it is clear from the context that it refers to a situation when you throw something at someone (or something with the animate attribute set). We will keep it as is.
